# Generated by Django 3.2.3 on 2024-01-30 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20240130_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FovoriteRecipes',
            new_name='FavoriteRecipes',
        ),
    ]
