# Generated by Django 3.2.3 on 2024-02-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_title_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
